services:
  db:
    # the service hosting your MySQL instance
    image: mysql:5.7 # the image and tag docker will pull from docker hub
    container_name: dev_db
    volumes:
      # this section allows you to configure persistence within multiple restarts
      - db_data:/var/lib/mysql
    restart: always # if the db crash somehow, restart it
    environment:
      # env variables, you usually set this to override existing ones
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    # MYSQL_USER: root
    # MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - backend

  api:
    container_name: dev_api
    image: NSA_API
    build: .
    restart: always
    environment:
      DB_HOST: db
    ports:
      - "5000:4000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge
volumes:
  db_data: 
