# Docker compose file for dev env, not used in production
services:
  db:
    image: mysql:8.2
    container_name: store_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "store_user"
      MYSQL_PASSWORD: "St0r3@U$er"
      MYSQL_DATABASE: "store_db"
      MYSQL_ROOT_PASSWORD: "RO0t@Root"
    ports:
      - "3307:3306"
    networks:
      - backend

  api:
    container_name: store-management-api
    image: store-management-api:latest
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "3000:5000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:
    driver: bridge

volumes:
  db_data: 
